trigger:
  branches:
    exclude:
      - '*'

parameters:
  - name: branchName
    type: string
    default: 'refs/heads/dev'
  - name: Environment
    type: string
    default: 'tst'
  - name: ApiEndpoint
    type: string
    default: 'dev'
  - name: SeleniumGrid
    type: string
    default: 'https://hub.browserstack.com/wd/hub/'
  - name: DeviceName
    type: string
    default: 'Windows'
  - name: BSOSVersion
    type: string
    default: '11'
  - name: BSBrowserVersion
    type: string
    default: 'latest'
  - name: Target
    type: string
    default: 'Edge'
  
resources:
  repositories:
    - repository: clientautomationreponew
      type: github
      name: DEFRA/nipts-pts-automation-tests
      ref: $(Build.SourceBranch)
      endpoint: DEFRA

stages:
  
  - stage: EnvironmentCheck
    displayName: EnvironmentCheck
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: EnvironmentCheck
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        TestDeviceName: ${{parameters.DeviceName}}
        OSVersionName: ${{parameters.BSOSVersion}}
        BrowserVersionName: ${{parameters.BSBrowserVersion}}
        dependsOn: ''
        targetBrowserName: ${{parameters.Target}}

  - stage: MacOSSafariBrowserRun
    displayName: MacOSSafariBrowserRun
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: macOSSafariBrowserRun
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        TestDeviceName: 'OS X'
        OSVersionName: 'Ventura'
        BrowserVersionName: 'latest'
        dependsOn: ''
        targetBrowserName: 'Chrome'

  - stage: MacOSChromeBrowserRun
    displayName: MacOSChromeBrowserRun
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: MacOSChromeBrowserRun
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        TestDeviceName: 'OS X'
        OSVersionName: 'Ventura'
        BrowserVersionName: '16.5'
        dependsOn: ''
        targetBrowserName: 'Safari'

  - stage: MacOSFirefoxBrowserRun
    displayName: MacOSFirefoxBrowserRun
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: MacOSFirefoxBrowserRun
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        TestDeviceName: 'OS X'
        OSVersionName: 'Ventura'
        BrowserVersionName: 'latest'
        dependsOn: ''
        targetBrowserName: 'Firefox'
