trigger: none

parameters:
  - name: branchName
    type: string
    default: 'refs/heads/dev'
  - name: Environment
    type: string
    default: 'tst'
  - name: ApiEndpoint
    type: string
    default: 'dev'
  - name: SeleniumGrid
    type: string
    default: 'https://hub.browserstack.com/wd/hub/'
  - name: DeviceName
    type: string
    default: 'Windows'
  - name: BSOSVersion
    type: string
    default: '11'
  - name: BSBrowserVersion
    type: string
    default: ''
  - name: Target
    type: string
    default: 'Edge'
  
schedules:
- cron: "0 14 * * Mon,Tue,Wed,Thu,Fri"
  displayName: Daily CrossBrowser build
  branches:
    include:
    - dev
    exclude:
    - feature/*
    - task/*
    - master
    

resources:
  repositories:
    - repository: clientautomationreponew
      type: github
      name: DEFRA/nipts-pts-automation-tests
      ref: $(Build.SourceBranch)
      endpoint: DEFRA

stages:
  
  - stage: EnvironmentCheck
    displayName: EnvironmentCheck
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: EnvironmentCheck
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        DeviceName: ${{parameters.DeviceName}}
        BSOSVersion: ${{parameters.BSOSVersion}}
        BSBrowserVersion: ''
        dependsOn: ''
        targetBrowserName: ${{parameters.Target}}


  - stage: IOSIphone14ChromeRun
    displayName: IOSIphone14ChromeRun
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: IOSIphone14ChromeRun
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        DeviceName: 'iPhone 14'
        BSOSVersion: '18'
        BSBrowserVersion: ''
        dependsOn: ''
        targetBrowserName: 'Chrome'

  - stage: IOSIpad12ChromeRun
    displayName: IOSIpad12ChromeRun
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: IOSIpad12ChromeRun
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        DeviceName: 'iPad Pro 12.9 2022'
        BSOSVersion: '16'
        BSBrowserVersion: ''
        dependsOn: ''
        targetBrowserName: 'Chrome'

  - stage: IOSIphoneSafari14Run
    displayName: IOSIphoneSafari14Run
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: IOSIphoneSafari14Run
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        DeviceName: 'iPhone 14'
        BSOSVersion: '18'
        BSBrowserVersion: ''
        dependsOn: ''
        targetBrowserName: 'safari'

  - stage: IOSIpad12SafariRun
    displayName: IOSIpad12SafariRun
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: IOSIpad12SafariRun
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        DeviceName: 'iPad Pro 12.9 2022'
        BSOSVersion: '16'
        BSBrowserVersion: ''
        dependsOn: ''
        targetBrowserName: 'safari'