trigger: none

parameters:
  - name: branchName
    type: string
    default: 'refs/heads/dev'
  - name: Environment
    type: string
    default: 'tst'
  - name: ApiEndpoint
    type: string
    default: 'dev'
  - name: SeleniumGrid
    type: string
    default: 'https://hub.browserstack.com/wd/hub/'
  - name: DeviceName
    type: string
    default: 'Windows'
  - name: BSOSVersion
    type: string
    default: '11'
  - name: Target
    type: string
    default: 'Edge'
  
schedules:
- cron: "0 16 * * Mon,Tue,Wed,Thu,Fri"
  displayName: Daily CrossBrowser build
  branches:
    include:
    - dev
    exclude:
    - feature/*
    - task/*
    - master
    

resources:
  repositories:
    - repository: clientautomationreponew
      type: github
      name: DEFRA/nipts-pts-automation-tests
      ref: $(Build.SourceBranch)
      endpoint: DEFRA

stages:
  
  - stage: EnvironmentCheck
    displayName: EnvironmentCheck
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: EnvironmentCheck
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        DeviceName: ${{parameters.DeviceName}}
        BSOSVersion: ${{parameters.BSOSVersion}}
        dependsOn: ''
        targetBrowserName: ${{parameters.Target}}

  - stage: AndroidSamsungRun
    displayName: AndroidSamsungRun
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: AndroidSamsungRun
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        DeviceName: 'Samsung Galaxy S23'
        BSOSVersion: '13.0'
        dependsOn: ''
        targetBrowserName: 'samsung'

  - stage: AndroidSamsungChromeRun
    displayName: AndroidSamsungChromeRun
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: AndroidSamsungChromeRun
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ${{parameters.SeleniumGrid}}  
        DeviceName: 'Samsung Galaxy S23'
        BSOSVersion: '13.0'
        dependsOn: ''
        targetBrowserName: 'Chrome'
