@Regression
Feature: ManualAddress

Update and verify Manual Address on Pets application Portal

Scenario: Enter Address Manually 
	Given that I navigate to the Pets application portal
	When  sign in with valid credentials with logininfo '<logininfo>'
	When  click on Welsh language 
	Then  verify next page '<nextPage>' is loaded
	When  click on Apply for a document
	Then  verify next page '<nextPage1>' is loaded
	When  select 'Nac ydyn' on Personal Details page
	And   click on continue
	Then  verify next page '<nextPage2>' is loaded
	When  enter your full name '<fullname>'
	And   click on continue
	Then  verify next page '<nextPage3>' is loaded
	When  click on enter address manually
	Then  verify next page '<nextPage4>' is loaded
	When  click on English language 
	Then  verify next page '<nextPage6>' is loaded
	When  click on Welsh language 
	Then  verify next page '<nextPage4>' is loaded
	When  enter address '<AddressLineOne>', '<AddressLineTwo>', '<TownOrCity>', '<County>', '<Postcode>'
	And   click on continue
	Then  verify next page '<nextPage5>' is loaded

	Examples: 
	| logininfo | nextPage                                        | nextPage1    | nextPage2 | nextPage3   | nextPage4     | nextPage5  | nextPage6             | fullname     | AddressLineOne | AddressLineTwo | TownOrCity | County  | Postcode |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | What is your address? | TestFullName | Addressline1   | Addressline2   | London     | England | SE3 0ER  |

	Scenario: Validate error messages on Manual Address page
	Given that I navigate to the Pets application portal
	When  sign in with valid credentials with logininfo '<logininfo>'
	When  click on Welsh language 
	Then  verify next page '<nextPage>' is loaded
	When  click on Apply for a document
	Then  verify next page '<nextPage1>' is loaded
	When  select 'Nac ydyn' on Personal Details page
	And   click on continue
	Then  verify next page '<nextPage2>' is loaded
	When  enter your full name '<fullname>'
	And   click on continue
	Then  verify next page '<nextPage3>' is loaded
	When  click on enter address manually
	Then  verify next page '<nextPage4>' is loaded
	When  enter address '<AddressLineOne>', '<AddressLineTwo>', '<TownOrCity>', '<County>', '<Postcode>'
	And   click on continue
	Then  verify error message '<errorMessage>' on manual address page

	Examples: 
	| logininfo | nextPage                                        | nextPage1    | nextPage2 | nextPage3   | nextPage4     | nextPage5  | fullname     | AddressLineOne                                                                                                                                                                                                                                              | AddressLineTwo                                                                                                                                                                                                                                              | TownOrCity                                                                                                                                                                                                                                                  | County  | Postcode                                                                                              | errorMessage                                                           |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName |                                                                                                                                                                                                                                                             | Addressline2                                                                                                                                                                                                                                                | London                                                                                                                                                                                                                                                      | England | ABCDEFGHIJKLMNO                                                                                       | Rhowch linell 1 eich cyfeiriad                                         |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName | Addressline1                                                                                                                                                                                                                                                | Addressline2                                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                             | England | SE3 0ER                                                                                               | Rhowch dref neu ddinas                                                 |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName | Addressline1                                                                                                                                                                                                                                                | Addressline2                                                                                                                                                                                                                                                | London                                                                                                                                                                                                                                                      | England |                                                                                                       | Rhowch god post                                                        |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName | ABCDEFGHIJKLMNOPHDJHGDFJKGFDKJBVKJDFNBKJFDHGKJSDHFGKDJHFKJSDHFKJHDSKJFHDKJHKJDHFKDHGJGJHSDFVJSDHFJDBFJEDDIUFGEISEHFKSDNFSBDFJFGFGFGHGHDHBVCJXCVKJDFGVKDFDGFVJHMDBFVJDFBVDFBVJHDFBVJDFBVJDFBVKJJHDFVJHDFVFDVDFVFDVFDVDFVDFVDFVDFNVKJDFBVJHDFJVHBDFJHJHDFVJHD | Addressline2                                                                                                                                                                                                                                                | London                                                                                                                                                                                                                                                      | England | SE3 0ER                                                                                               | Rhowch linell 1 eich cyfeiriad gan ddefnyddio 250 o gymeriadau neu lai |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName | Addressline1                                                                                                                                                                                                                                                | ABCDEFGHIJKLMNOPHDJHGDFJKGFDKJBVKJDFNBKJFDHGKJSDHFGKDJHFKJSDHFKJHDSKJFHDKJHKJDHFKDHGJGJHSDFVJSDHFJDBFJEDDIUFGEISEHFKSDNFSBDFJFGFGFGHGHDHBVCJXCVKJDFGVKDFDGFVJHMDBFVJDFBVDFBVJHDFBVJDFBVJDFBVKJJHDFVJHDFVFDVDFVFDVFDVDFVDFVDFVDFNVKJDFBVJHDFJVHBDFJHJHDFVJHD | London                                                                                                                                                                                                                                                      | England | SE3 0ER                                                                                               | Rhowch linell 2 eich cyfeiriad gan ddefnyddio 250 o gymeriadau neu lai |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName | Addressline1                                                                                                                                                                                                                                                | Addressline2                                                                                                                                                                                                                                                | ABCDEFGHIJKLMNOPHDJHGDFJKGFDKJBVKJDFNBKJFDHGKJSDHFGKDJHFKJSDHFKJHDSKJFHDKJHKJDHFKDHGJGJHSDFVJSDHFJDBFJEDDIUFGEISEHFKSDNFSBDFJFGFGFGHGHDHBVCJXCVKJDFGVKDFDGFVJHMDBFVJDFBVDFBVJHDFBVJDFBVJDFBVKJJHDFVJHDFVFDVDFVFDVFDVDFVDFVDFVDFNVKJDFBVJHDFJVHBDFJHJHDFVJHD | England | SE3 0ER                                                                                               | Rhowch dref neu ddinas gan ddefnyddio 250 o gymeriadau neu lai |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName | Addressline1                                                                                                                                                                                                                                                | Addressline2                                                                                                                                                                                                                                                | London                                                                                                                                                                                                                                                      | ABCDEFGHIJKLMNOPHDJHGDFJKGFDKJBVKJDFNBKJFDHGKJSDHFGKDJHFKJSDHFKJHDSKJFHDKJHKJDHFKDHGJGJHSDFVJSDHFJDBF |SE10 0BP | Rhowch sir gan ddefnyddio 100 o gymeriadau neu lai |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName | Addressline1                                                                                                                                                                                                                                                | Addressline2                                                                                                                                                                                                                                                | London                                                                                                                                                                                                                                                      | England | ABCDEFGHIJKLMNOPQRSTUV                                                                                | Rhowch god post llawn yn y fformat cywir                                         |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName | Addressline1                                                                                                                                                                                                                                                | Addressline2                                                                                                                                                                                                                                                | London                                                                                                                                                                                                                                                      | England | BT2345J                                                                                               | Rhowch god post yng Nghymru                                         |
	| test      | Dogfennau teithio gydol oes i anifeiliaid anwes | manylion chi | Beth yw   | ch cod post | ch cyfeiriad? | ch rhif ff | TestFullName | Addressline1                                                                                                                                                                                                                                                | Addressline2                                                                                                                                                                                                                                                | London                                                                                                                                                                                                                                                      | England | SE10$%^                                                                                               | Rhowch god post llawn yn y fformat cywir                                         |
